# THIS FILE WAS AUTOMATICALLY GENERATED AT 2022-04-07T20:46:13.280204
#####################################################################

from typing import Optional

from sqlmodel import SQLModel, Field

from src.utils.meta import hash_field_to_uuid


class SynthParams(SQLModel):
    id: Optional[str] = Field(primary_key=True, default=None)
    hyphen__0: float = Field(alias="0")
    Master_Volume_1: float = Field(alias="1")
    Filter_Type_2: float = Field(alias="2")
    Filter_Cutoff_3: float = Field(alias="3")
    Filter_Resonance_4: float = Field(alias="4")
    Fitler_Keyfollow_5: float = Field(alias="5")
    Filter_Contour_6: float = Field(alias="6")
    Filter_Attack_7: float = Field(alias="7")
    Filter_Decay_8: float = Field(alias="8")
    Filter_Sustain_9: float = Field(alias="9")
    Filter_Release_10: float = Field(alias="10")
    Amp_Attack_11: float = Field(alias="11")
    Amp_Decay_12: float = Field(alias="12")
    Amp_Sustain_13: float = Field(alias="13")
    Amp_Release_14: float = Field(alias="14")
    Osc_1_Volume_15: float = Field(alias="15")
    Osc_2_Volume_16: float = Field(alias="16")
    Osc_3_Volume_17: float = Field(alias="17")
    Osc_Mastertune_18: float = Field(alias="18")
    Osc_1_Tune_19: float = Field(alias="19")
    Osc_2_Tune_20: float = Field(alias="20")
    Osc_1_Fine_Tune_21: float = Field(alias="21")
    Osc_2_Fine_Tune_22: float = Field(alias="22")
    Osc_1_Waveform_23: float = Field(alias="23")
    Osc_1_Waveform_24: float = Field(alias="24")
    Osc_Sync_25: float = Field(alias="25")
    Lfo_1_Waveform_26: float = Field(alias="26")
    Lfo_2_Waveform_27: float = Field(alias="27")
    Lfo_1_Rate_28: float = Field(alias="28")
    Lfo_2_Rate_29: float = Field(alias="29")
    Lfo_1_Amount_30: float = Field(alias="30")
    Lfo_2_Amount_31: float = Field(alias="31")
    Lfo_1_Destination_32: float = Field(alias="32")
    Lfo_2_Destination_33: float = Field(alias="33")
    Lfo_1_Phase_34: float = Field(alias="34")
    Lfo_2_Phase_35: float = Field(alias="35")
    Osc_2_FM_36: float = Field(alias="36")
    Osc_2_Phase_37: float = Field(alias="37")
    Osc_2_PW_38: float = Field(alias="38")
    Osc_2_Phase_39: float = Field(alias="39")
    Transpose_40: float = Field(alias="40")
    Free_Ad_Attack_41: float = Field(alias="41")
    Free_Ad_Decay_42: float = Field(alias="42")
    Free_Ad_Amount_43: float = Field(alias="43")
    Free_Ad_Destination_44: float = Field(alias="44")
    Lfo_1_Sync_45: float = Field(alias="45")
    Lfo_1_Keytrigger_46: float = Field(alias="46")
    Lfo_2_Sync_47: float = Field(alias="47")
    Lfo_2_Keytrigger_48: float = Field(alias="48")
    Portamento_Amount_49: float = Field(alias="49")
    Portamento_Mode_50: float = Field(alias="50")
    Voices_51: float = Field(alias="51")
    Velocity_Volume_52: float = Field(alias="52")
    Velocity_Contour_53: float = Field(alias="53")
    Velocity_Filter_54: float = Field(alias="54")
    Pitchwheel_Cutoff_55: float = Field(alias="55")
    Pitchwheel_Pitch_56: float = Field(alias="56")
    Ringmodulation_57: float = Field(alias="57")
    Chorus_1_Enable_58: float = Field(alias="58")
    Chorus_2_Enable_59: float = Field(alias="59")
    Reverb_Wet_60: float = Field(alias="60")
    Reverb_Decay_61: float = Field(alias="61")
    Reverb_Pre_Delay_62: float = Field(alias="62")
    Reverb_High_Cut_63: float = Field(alias="63")
    Reverb_Low_Cut_64: float = Field(alias="64")
    Osc_Bitcrusher_65: float = Field(alias="65")
    Master_High_Pass_66: float = Field(alias="66")
    Master_Detune_67: float = Field(alias="67")
    Vintage_Noise_68: float = Field(alias="68")
    Panic_69: float = Field(alias="69")
    MIDI_LEARN_70: float = Field(alias="70")
    Envelope_Destination_71: float = Field(alias="71")
    Envelope_Speed_72: float = Field(alias="72")
    Envelope_Amount_73: float = Field(alias="73")
    Envelope_One_Shot_Mode_74: float = Field(alias="74")
    Envelope_Fix_Tempo_75: float = Field(alias="75")
    Envelope_Reset_76: float = Field(alias="76")
    Filter_Drive_77: float = Field(alias="77")
    Delay_Wet_78: float = Field(alias="78")
    Delay_Time_79: float = Field(alias="79")
    Delay_Sync_80: float = Field(alias="80")
    Delay_x2_L_81: float = Field(alias="81")
    Delay_x2_R_82: float = Field(alias="82")
    Delay_High_Shelf_83: float = Field(alias="83")
    Delay_Low_Shelf_84: float = Field(alias="84")
    Delay_Feedback_85: float = Field(alias="85")
    MIDI_Clear_86: float = Field(alias="86")
    MIDI_Lock_87: float = Field(alias="87")
    Bypass_88: float = Field(alias="88")

    class Config:
        validate_all = True

    _auto_uuid = hash_field_to_uuid("id")


class SynthParamsTable(SynthParams, table=True):
    __tablename__ = "SynthParams"
